# Generated by Django 3.2.6 on 2021-10-13 17:13

from django.db import migrations, models
import djpaddle.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djpaddle', '0005_replayedevent_webhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=1024, null=True)),
                ('base_price', models.FloatField()),
                ('sale_price', models.FloatField(null=True)),
                ('currency', djpaddle.fields.PaddleCurrencyCodeField(help_text='Three-letter ISO currency code', max_length=3)),
                ('icon', models.CharField(max_length=1024, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
