# Generated by Django 3.2.6 on 2021-10-19 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djpaddle', '0006_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('event_time', models.DateTimeField()),
                ('email', models.EmailField(max_length=254)),
                ('quantity', models.IntegerField()),
                ('checkout_id', models.CharField(max_length=64)),
                ('marketing_consent', models.BooleanField()),
                ('source', models.URLField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djpaddle.product')),
                ('subscriber', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
